name: Ray.Di
safe: true
lsi: false

url: https://github.com/ray-di/Ray.Di
title: Ray.Di

markdown: kramdown
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: rouge
